import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './Navbar'
import Footer from './section/Footer'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Hello my Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
